[project]
name = "arxiv-curator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "feedparser>=6.0.12",
    "loguru>=0.7.3",
    "requests>=2.32.5",
]
